-- Naeron uçak ve simülatör listesi (bi_aircrafts_simulators): Filo ekranının kaynağı.
CREATE TABLE IF NOT EXISTS public.naeron_bi_aircrafts_simulators (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "vm_ID" text,
  type text,
  "regNo" text,
  "aircraftType" text,
  external text,
  "outOfInventory" text,
  color text,
  "tachoType" text,
  "flightTime" text,
  tacho text,
  "engineType" text,
  complex text,
  "lastBaseTo" text,
  "lastFlightDate" timestamp(3),
  "underMaintenance" text,
  "UEGGS" timestamp(3),
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_aircrafts_simulators_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_aircrafts_simulators ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.odt_naeron_upsert_aircrafts_simulators(p_rows jsonb)
RETURNS integer LANGUAGE sql SECURITY INVOKER SET search_path = public AS $$
  WITH x AS (
    INSERT INTO public.naeron_bi_aircrafts_simulators ("m_ID", "vm_ID", type, "regNo", "aircraftType", external, "outOfInventory", color, "tachoType", "flightTime", tacho, "engineType", complex, "lastBaseTo", "lastFlightDate", "underMaintenance", "UEGGS", "_lastRowStatus", "_lastRowUpdate")
    SELECT "m_ID", "vm_ID", type, "regNo", "aircraftType", external, "outOfInventory", color, "tachoType", "flightTime", tacho, "engineType", complex, "lastBaseTo", "lastFlightDate", "underMaintenance", "UEGGS", "_lastRowStatus", "_lastRowUpdate"
    FROM jsonb_populate_recordset(NULL::public.naeron_bi_aircrafts_simulators, p_rows)
    WHERE "m_ID" IS NOT NULL
    ON CONFLICT ("m_ID") DO UPDATE SET "vm_ID" = EXCLUDED."vm_ID", type = EXCLUDED.type, "regNo" = EXCLUDED."regNo", "aircraftType" = EXCLUDED."aircraftType", external = EXCLUDED.external, "outOfInventory" = EXCLUDED."outOfInventory", color = EXCLUDED.color, "tachoType" = EXCLUDED."tachoType", "flightTime" = EXCLUDED."flightTime", tacho = EXCLUDED.tacho, "engineType" = EXCLUDED."engineType", complex = EXCLUDED.complex, "lastBaseTo" = EXCLUDED."lastBaseTo", "lastFlightDate" = EXCLUDED."lastFlightDate", "underMaintenance" = EXCLUDED."underMaintenance", "UEGGS" = EXCLUDED."UEGGS", "_lastRowStatus" = EXCLUDED."_lastRowStatus", "_lastRowUpdate" = EXCLUDED."_lastRowUpdate"
    RETURNING 1)
  SELECT count(*)::int FROM x
$$;

REVOKE ALL ON FUNCTION public.odt_naeron_upsert_aircrafts_simulators(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.odt_naeron_upsert_aircrafts_simulators(jsonb) TO service_role;
