CREATE TABLE public.naeron_bi_corporate_labels (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  code text,
  name text,
  color text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_corporate_labels_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_corporate_labels ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_currencies (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  name text,
  shortcode text,
  symbol text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_currencies_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_currencies ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_employees (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "vm_ID" integer,
  active integer,
  title text,
  "shortCode" text,
  "firstName" text,
  "lastName" text,
  "regNo" text,
  gender text,
  constricted text,
  fi integer,
  obs text,
  tki text,
  "controlInstructor" text,
  "startDate" timestamp(3),
  "endDate" timestamp(3),
  "facilityID" integer,
  gsm text,
  email text,
  "workTypeID" integer,
  "lastFlight" text,
  "supervisorID" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  "birthDate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_employees_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_employees ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_facilities (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  icao text,
  name text,
  latitude text,
  longitude text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_facilities_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_facilities ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_fleets (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  name text,
  "startDate" timestamp(3),
  "trainingType" text,
  archive text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_fleets_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_fleets ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_flights (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "planID" integer,
  external text,
  "exSchoolName_" text,
  type text,
  "flightDate" timestamp(3),
  "landingDate" timestamp(3),
  "OffBlock" integer,
  "OnBlock" integer,
  duration integer,
  "BlockTime" integer,
  "plannedOffBlock" integer,
  "plannedOnBlock" integer,
  "TakeOff" integer,
  "Landing" integer,
  "flightDuration" integer,
  aircraft text,
  "a_ID" integer,
  "aircraftName_" text,
  "studentVMID" text,
  "s_Type" text,
  "s_ID" integer,
  "studentName_" text,
  "student2VMID" text,
  "s_Type2" text,
  "s_ID2" text,
  "student2Name_" text,
  "instructorVMID" text,
  "i_Type" text,
  "i_ID" integer,
  "instructorName_" text,
  "observerVMID" text,
  "o_Type" text,
  "o_ID" integer,
  "observerName_" text,
  "baseFromID" integer,
  "baseFromName_" text,
  "baseToID" integer,
  "baseToName_" text,
  route text,
  "routeName_" text,
  "dutyName_" text,
  note text,
  tacho text,
  "formNo" text,
  "landingCount" integer,
  "obsPos" integer,
  "obsPosName_" text,
  night text,
  rt text,
  ifr text,
  "IFRduration" text,
  complex text,
  nm150 text,
  nm300 text,
  spic text,
  mcc text,
  "engineType" text,
  "noCalcStats" text,
  "noAssessment" text,
  "progressCheck" text,
  "dutyRetake" text,
  control text,
  "controlResult" text,
  navigation text,
  "planShift" text,
  "planShiftName_" text,
  "planShiftNote" text,
  "paidFlight" text,
  afmlcontrol integer,
  realized integer,
  canceled text,
  "cancelNote" text,
  incomplete text,
  "hasFault" text,
  "faultDesc" text,
  "faultState" text,
  "_flightStatus" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_flights_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_flights_idx_s_id ON public.naeron_bi_flights ("s_ID");
ALTER TABLE public.naeron_bi_flights ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_groups (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "facilityID" integer,
  "fleetID" integer,
  code text,
  "trainingID" integer,
  "startDate" timestamp(3),
  archive text,
  "revisionID" integer,
  "inTheory" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_groups_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_groups ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_students (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "vm_ID" integer,
  "corpLabelID" integer,
  "fleetID" integer,
  "shortCode" text,
  "firstName" text,
  "lastName" text,
  "studentNo" text,
  gender text,
  "identityNo" text,
  "licenceNo" text,
  "lastFlight" text,
  "lastDuty" text,
  "trainingStatus" text,
  "facilityID" text,
  gsm text,
  email text,
  "inTheory" text,
  "inControl" text,
  "suspendFlights" text,
  "actualTrainingName" text,
  "actualPhaseName" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  "birthDate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_students_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_students_idx_corp_label ON public.naeron_bi_students ("corpLabelID");
ALTER TABLE public.naeron_bi_students ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_student_certificates (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "studentID" integer,
  "documentNo" text,
  "startDate" timestamp(3),
  "endDate" timestamp(3),
  note text,
  archive integer,
  name text,
  visibility text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_student_certificates_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_student_certificates_idx_student_id ON public.naeron_bi_student_certificates ("studentID");
ALTER TABLE public.naeron_bi_student_certificates ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_student_contracts (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "studentID" integer,
  subject text,
  "contractNo" text,
  note text,
  "signDate" timestamp(3),
  "signerID" integer,
  "signerName" text,
  "contractStatus" text,
  price text,
  payed text,
  "currencyID" integer,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_student_contracts_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_student_contracts_idx_student_id ON public.naeron_bi_student_contracts ("studentID");
ALTER TABLE public.naeron_bi_student_contracts ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_student_installments (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "studentID" integer,
  "contractID" integer,
  "installmentDate" timestamp(3),
  name text,
  price text,
  currency integer,
  status text,
  note text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_student_installments_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_student_installments_idx_student_id ON public.naeron_bi_student_installments ("studentID");
ALTER TABLE public.naeron_bi_student_installments ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_student_payments (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "studentID" integer,
  "contractID" integer,
  "paymentDate" timestamp(3),
  "paymentNo" text,
  amount text,
  "currencyID" integer,
  exchange text,
  note text,
  "bankAccountID" text,
  "creatorID" integer,
  "createDate" timestamp(3),
  "creatorName" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_student_payments_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_student_payments ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_student_trainings (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  "studentID" integer,
  "groupID" text,
  "trainingID" integer,
  "revisionID" text,
  "contractID" integer,
  finance text,
  duration text,
  done text,
  "pDone" text,
  "trainingStatus" text,
  note text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_student_trainings_uq_pk_key UNIQUE ("m_ID")
);
CREATE INDEX naeron_bi_student_trainings_idx_student_id ON public.naeron_bi_student_trainings ("studentID");
ALTER TABLE public.naeron_bi_student_trainings ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.naeron_bi_trainings (
  _sync_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "m_ID" integer,
  name text,
  "itemOrder" integer,
  "trainingType" text,
  "_lastRowStatus" text,
  "_lastRowUpdate" timestamp(3),
  PRIMARY KEY (_sync_id),
  CONSTRAINT naeron_bi_trainings_uq_pk_key UNIQUE ("m_ID")
);
ALTER TABLE public.naeron_bi_trainings ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_access (
  user_id integer NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_write boolean NOT NULL DEFAULT false,
  updated_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id)
);
ALTER TABLE public.northfly_odt_access ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_contract_pdf_links (
  contract_id integer NOT NULL,
  student_id integer NOT NULL,
  contract_subject varchar(255) NOT NULL DEFAULT '',
  sign_date date,
  storage_path varchar(1024) NOT NULL,
  download_token varchar(128) NOT NULL,
  full_url varchar(2048) NOT NULL,
  imported_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (contract_id)
);
CREATE INDEX northfly_odt_contract_pdf_links_idx_student ON public.northfly_odt_contract_pdf_links (student_id);
CREATE INDEX northfly_odt_contract_pdf_links_idx_sign ON public.northfly_odt_contract_pdf_links (student_id, sign_date);
ALTER TABLE public.northfly_odt_contract_pdf_links ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_email_access (
  email varchar(190) NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_write boolean NOT NULL DEFAULT false,
  updated_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (email)
);
ALTER TABLE public.northfly_odt_email_access ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_kaynak_saat (
  source_id varchar(32) NOT NULL,
  checked_at timestamp(3) NOT NULL,
  ok boolean NOT NULL,
  ms integer,
  error_text varchar(190),
  ozet varchar(190),
  PRIMARY KEY (source_id)
);
ALTER TABLE public.northfly_odt_kaynak_saat ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_nazari_attempts (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  student_id integer NOT NULL,
  exam_date date NOT NULL,
  score numeric(5,2) NOT NULL,
  recorded_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX northfly_odt_nazari_attempts_idx_nazari_student ON public.northfly_odt_nazari_attempts (student_id);
CREATE INDEX northfly_odt_nazari_attempts_idx_nazari_student_exam ON public.northfly_odt_nazari_attempts (student_id, exam_date);
ALTER TABLE public.northfly_odt_nazari_attempts ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_nazari_legacy_pass (
  student_id integer NOT NULL,
  recorded_at timestamp(3) NOT NULL DEFAULT now(),
  puan_kaydi_note varchar(200),
  exam_attempt_no integer,
  exam_date date,
  PRIMARY KEY (student_id)
);
CREATE INDEX northfly_odt_nazari_legacy_pass_idx_nzlp_recorded ON public.northfly_odt_nazari_legacy_pass (recorded_at);
ALTER TABLE public.northfly_odt_nazari_legacy_pass ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_nazari_subjects (
  "m_ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  code varchar(64) NOT NULL DEFAULT '',
  name varchar(255) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  counts_toward_total boolean NOT NULL DEFAULT true,
  pass_min_score numeric(5,2) NOT NULL DEFAULT 70.00,
  PRIMARY KEY ("m_ID"),
  CONSTRAINT northfly_odt_nazari_subjects_uq_nazari_code_key UNIQUE (code)
);
CREATE INDEX northfly_odt_nazari_subjects_idx_nazari_sort ON public.northfly_odt_nazari_subjects (sort_order);
ALTER TABLE public.northfly_odt_nazari_subjects ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_nazari_subject_scores (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  student_id integer NOT NULL,
  subject_id integer NOT NULL,
  score numeric(5,2) NOT NULL,
  exam_date date NOT NULL,
  recorded_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);
CREATE INDEX northfly_odt_nazari_subject_scores_idx_nss_student ON public.northfly_odt_nazari_subject_scores (student_id);
CREATE INDEX northfly_odt_nazari_subject_scores_idx_nss_subject ON public.northfly_odt_nazari_subject_scores (subject_id);
CREATE INDEX northfly_odt_nazari_subject_scores_idx_nss_st_sub ON public.northfly_odt_nazari_subject_scores (student_id, subject_id);
ALTER TABLE public.northfly_odt_nazari_subject_scores ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_pic_takip (
  student_id integer NOT NULL,
  katilacagi_tarihler text NOT NULL,
  updated_at timestamp(3) NOT NULL,
  PRIMARY KEY (student_id)
);
ALTER TABLE public.northfly_odt_pic_takip ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_seo_rows (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  run_date date NOT NULL,
  kind varchar(10) NOT NULL,
  wp_id integer NOT NULL,
  link varchar(500) NOT NULL DEFAULT '',
  title varchar(250) NOT NULL DEFAULT '',
  score smallint,
  keyword varchar(190) NOT NULL DEFAULT '',
  seo_title varchar(250) NOT NULL DEFAULT '',
  description varchar(500) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  CONSTRAINT northfly_odt_seo_rows_run_kind_wp_key UNIQUE (run_date, kind, wp_id)
);
CREATE INDEX northfly_odt_seo_rows_run_date ON public.northfly_odt_seo_rows (run_date);
ALTER TABLE public.northfly_odt_seo_rows ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_seo_runs (
  run_date date NOT NULL,
  started_at timestamp(3) NOT NULL,
  finished_at timestamp(3),
  posts_n integer NOT NULL DEFAULT 0,
  pages_n integer NOT NULL DEFAULT 0,
  ok boolean NOT NULL DEFAULT false,
  error_text varchar(250),
  PRIMARY KEY (run_date)
);
ALTER TABLE public.northfly_odt_seo_runs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_student_bits (
  student_id integer NOT NULL,
  cpl_ir_me_manual boolean,
  atpl_theory_manual boolean,
  updated_at timestamp(3) NOT NULL DEFAULT now(),
  cpl_manual boolean,
  ir_manual boolean,
  me_manual boolean,
  cpl_plan_manual boolean,
  ir_plan_manual boolean,
  me_plan_manual boolean,
  atpl_plan_manual boolean,
  cpl_flown_school varchar(16),
  ir_flown_school varchar(16),
  me_flown_school varchar(16),
  atpl_flown_school varchar(16),
  PRIMARY KEY (student_id)
);
ALTER TABLE public.northfly_odt_student_bits ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_student_finance_prefs (
  student_id integer NOT NULL,
  email_override varchar(255),
  updated_at timestamp(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (student_id)
);
ALTER TABLE public.northfly_odt_student_finance_prefs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_student_notes (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  student_id integer NOT NULL,
  body text NOT NULL,
  created_at timestamp(3) NOT NULL,
  author_user_id integer,
  author_name varchar(190) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);
CREATE INDEX northfly_odt_student_notes_idx_student_created ON public.northfly_odt_student_notes (student_id, created_at);
CREATE INDEX northfly_odt_student_notes_idx_student_id ON public.northfly_odt_student_notes (student_id);
ALTER TABLE public.northfly_odt_student_notes ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_users (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email varchar(190) NOT NULL,
  full_name varchar(190) NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  is_super boolean NOT NULL DEFAULT false,
  created_at timestamp(3) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT northfly_odt_users_email_key UNIQUE (email)
);
ALTER TABLE public.northfly_odt_users ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_odt_user_modules (
  user_id integer NOT NULL,
  module_id varchar(32) NOT NULL,
  PRIMARY KEY (user_id, module_id)
);
ALTER TABLE public.northfly_odt_user_modules ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_wapi_auto (
  id smallint NOT NULL,
  enabled boolean NOT NULL DEFAULT false,
  last_run timestamp(3),
  PRIMARY KEY (id)
);
ALTER TABLE public.northfly_wapi_auto ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_wapi_sends (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(3) NOT NULL,
  author_email varchar(190) NOT NULL,
  integration_id integer NOT NULL,
  phone varchar(32) NOT NULL,
  kind varchar(16) NOT NULL,
  body text,
  template_name varchar(190),
  ok boolean NOT NULL DEFAULT false,
  error_text varchar(500),
  message_id varchar(190),
  PRIMARY KEY (id)
);
CREATE INDEX northfly_wapi_sends_created_at ON public.northfly_wapi_sends (created_at);
ALTER TABLE public.northfly_wapi_sends ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_wp_forms (
  form_id integer NOT NULL,
  title varchar(190) NOT NULL,
  field_labels text,
  field_types text,
  active boolean NOT NULL DEFAULT false,
  updated_at timestamp(3) NOT NULL,
  active_manual boolean NOT NULL DEFAULT false,
  PRIMARY KEY (form_id)
);
ALTER TABLE public.northfly_wp_forms ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.northfly_wp_form_entries (
  entry_id integer NOT NULL,
  form_id integer NOT NULL,
  entry_date timestamp(3),
  status varchar(40),
  fields_json text,
  ad varchar(190),
  telefon varchar(80),
  eposta varchar(190),
  ozet varchar(220),
  pulled_at timestamp(3) NOT NULL,
  PRIMARY KEY (entry_id)
);
CREATE INDEX northfly_wp_form_entries_form_id ON public.northfly_wp_form_entries (form_id);
CREATE INDEX northfly_wp_form_entries_entry_date ON public.northfly_wp_form_entries (entry_date);
ALTER TABLE public.northfly_wp_form_entries ENABLE ROW LEVEL SECURITY;

-- MySQL'deki `text + 0` davranışını (baştaki sayıyı al, yoksa 0) taklit eder.
CREATE OR REPLACE FUNCTION public.mysql_num(v text)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT COALESCE(substring(btrim(v) from '^[+-]?[0-9]+(?:\.[0-9]+)?')::numeric, 0)
$$;
